I did task 6-10
aklutskaya/Anna_Klutskaya_AT_G8 pull request #15
Opened 2023-10-27 17:43 UTC by aklutskaya

2023-10-27 18:10 UTC, IrynaAlesiyuk requested changes

2023-10-27 18:10 UTC, IrynaAlesiyuk commented on src/homework/day8/ListTasks/TaskSix.java
> +        Pattern pattern = Pattern.compile("[аоуея]");
I think that we have more Vowels in RU

2023-10-27 18:10 UTC, IrynaAlesiyuk commented on src/homework/day8/ListTasks/TaskSeven.java
> +            if (element.contains("-") || element.contains(" ")) {
I think this approach will fail if String hava space in the beggining or in the end

2023-10-27 18:10 UTC, IrynaAlesiyuk commented on src/homework/day8/ListTasks/TaskSeven.java
> +            if (element.contains("-") || element.contains(" ")) {
And "-" in the beggining and end

2023-10-27 18:10 UTC, IrynaAlesiyuk commented on src/homework/day8/ListTasks/TaskNine.java
> +            System.out.print(doubles.get(i) + " ");
это вернет скорее dooble, а нужно только целую часть

2023-10-27 18:22 UTC, aklutskaya commented on src/homework/day8/ListTasks/TaskSix.java
> +        Pattern pattern = Pattern.compile("[аоуея]");
Added more vowels

2023-10-27 18:33 UTC, aklutskaya commented on src/homework/day8/ListTasks/TaskNine.java
> +            System.out.print(doubles.get(i) + " ");
fixed

2023-10-30 20:14 UTC, aklutskaya commented on src/homework/day8/ListTasks/TaskSeven.java
> +            if (element.contains("-") || element.contains(" ")) {
fixed

2023-10-31 08:22 UTC, IrynaAlesiyuk approved these changes

2023-10-31 10:56 UTC, merged